### ISSUE TITLE
自己找的训练数据训练完成之后输入测试报错

### ISSUE THREAD

**Issue by zhangchangrui** [Determined22/zh-NER-TF#24]
============= demo =============
Please input your sentence:
宏远信息科技有限公司
Traceback (most recent call last):
  File "/Users/zhangchangrui/Downloads/zh-NER-TF-master/main.py", line 123, in <module>
    ORG = get_entity(tag, demo_sent)
  File "/Users/zhangchangrui/Downloads/zh-NER-TF-master/utils.py", line 19, in get_entity
    ORG = get_ORG_entity(tag_seq, char_seq)
  File "/Users/zhangchangrui/Downloads/zh-NER-TF-master/utils.py", line 81, in get_ORG_entity
    org += char
UnboundLocalError: local variable 'org' referenced before assignment

**Comment by Determined22** [comment]
Hi,
这个测试句子直接用我的模型可以正确识别：
============= demo =============
INFO:tensorflow:Restoring parameters from ./data_path_save/1521112368/checkpoints/model-31680
Restoring parameters from ./data_path_save/1521112368/checkpoints/model-31680
Please input your sentence:
宏远信息科技有限公司
PER: []
LOC: []
ORG: ['宏远信息科技有限公司']

报错的原因我觉得应该是模型训练不充分，导致产生了不符合规则的输出序列。可参考： #6

**Comment by xycim** [comment]
@zhangchangrui 请问您是输入制作pkl数据的呀？作者说用data.py里面的vocab_build函数。但是总是失败。能否告诉我一下您的指令？万分感激。
