### ISSUE TITLE
word2vec

### ISSUE THREAD

**Issue by wssgzxh** [Determined22/zh-NER-TF#31]
您好,我是新手,我想知道词向量是如何添加的,格式是什么样子的?

**Comment by wssgzxh** [comment]
Traceback (most recent call last):
  File "main.py", line 121, in <module>
    PER, LOC, ORG = get_entity(tag, demo_sent)
  File "/home/wssgzxh/桌面/zh-NER-TF-master/utils.py", line 16, in get_entity
    LOC = get_LOC_entity(tag_seq, char_seq)
  File "/home/wssgzxh/桌面/zh-NER-TF-master/utils.py", line 56, in get_LOC_entity
    loc += char
UnboundLocalError: local variable 'loc' referenced before assignment

我在demo的时候出现了这个，这是为何？

**Comment by Determined22** [comment]
Hi,
这个问题是因为模型输出的标签序列是不合规则的，产生不合规则的输出序列可能是因为模型训练不充分。可参考 #6 。
