### ISSUE TITLE
楼主，这个错是什么情况？

### ISSUE THREAD

**Issue by chyang2015** [Determined22/zh-NER-TF#63]
![image](https://user-images.githubusercontent.com/12468247/47950550-c21f9580-df8e-11e8-972b-323e9a75e423.png)

**Comment by hipparic** [comment]
应该是你的test_data有问题，有空字符。

**Comment by bluesky632** [comment]
你好，请问你解决了吗？我也遇到了同样的错误

**Comment by hipparic** [comment]
能否贴下你的test_data的数据。@bluesky632

**Comment by rorovic** [comment]
我也遇到了同样的问题 Traceback (most recent call last):
  File "crf_djy_train.py", line 479, in <module>
    model.train(train=train_data, dev=train_data)  # use test_data as the dev_data to see overfitting phenomena
  File "crf_djy_train.py", line 303, in train
    self.run_one_epoch(sess, train, dev, self.tag2label, epoch, saver)
  File "crf_djy_train.py", line 362, in run_one_epoch
    label_list_dev, seq_len_list_dev = self.dev_one_epoch(sess, dev)
  File "crf_djy_train.py", line 397, in dev_one_epoch
    label_list_, seq_len_list_ = self.predict_one_batch(sess, seqs)
  File "crf_djy_train.py", line 417, in predict_one_batch
    viterbi_seq, _ = viterbi_decode(logit[:seq_len], transition_params)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/crf/python/ops/crf.py", line 313, in viterbi_decode
    trellis[0] = score[0]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by bluesky632** [comment]
> 我也遇到了同样的问题 Traceback (most recent call last):
> File "crf_djy_train.py", line 479, in 
> model.train(train=train_data, dev=train_data) # use test_data as the dev_data to see overfitting phenomena
> File "crf_djy_train.py", line 303, in train
> self.run_one_epoch(sess, train, dev, self.tag2label, epoch, saver)
> File "crf_djy_train.py", line 362, in run_one_epoch
> label_list_dev, seq_len_list_dev = self.dev_one_epoch(sess, dev)
> File "crf_djy_train.py", line 397, in dev_one_epoch
> label_list_, seq_len_list_ = self.predict_one_batch(sess, seqs)
> File "crf_djy_train.py", line 417, in predict_one_batch
> viterbi_seq, _ = viterbi_decode(logit[:seq_len], transition_params)
> File "/usr/lib/python2.7/site-packages/tensorflow/contrib/crf/python/ops/crf.py", line 313, in viterbi_decode
> trellis[0] = score[0]
> IndexError: index 0 is out of bounds for axis 0 with size 0

我的好像是数据集里存在空格的情况，就是字与标签没有对应起来，你看一下你的数据集存不存在这个问题

**Comment by Greennut** [comment]
这是因为data.py有bug, read_corpus 不能处理连续两个空行，要么确保你的数据没有连续两个空行出现，要么改源代码`        else
            data.append((sent_, tag_))
            sent_, tag_ = [], []` 为 `        elif sent_ !=[] and tag_ !=[]: # 
            data.append((sent_, tag_))
            sent_, tag_ = [], []`

**Comment by Bigchen8013** [comment]
> 我也遇到了同样的问题 Traceback (most recent call last):
> File "crf_djy_train.py", line 479, in
> model.train(train=train_data, dev=train_data) # use test_data as the dev_data to see overfitting phenomena
> File "crf_djy_train.py", line 303, in train
> self.run_one_epoch(sess, train, dev, self.tag2label, epoch, saver)
> File "crf_djy_train.py", line 362, in run_one_epoch
> label_list_dev, seq_len_list_dev = self.dev_one_epoch(sess, dev)
> File "crf_djy_train.py", line 397, in dev_one_epoch
> label_list_, seq_len_list_ = self.predict_one_batch(sess, seqs)
> File "crf_djy_train.py", line 417, in predict_one_batch
> viterbi_seq, _ = viterbi_decode(logit[:seq_len], transition_params)
> File "/usr/lib/python2.7/site-packages/tensorflow/contrib/crf/python/ops/crf.py", line 313, in viterbi_decode
> trellis[0] = score[0]
> IndexError: index 0 is out of bounds for axis 0 with size 0

是测试数据集的格式有问题
