### ISSUE TITLE
楼主我这个错误是什么情况呀？要怎么改呀？谢谢

### ISSUE THREAD

**Issue by fengchangmin666** [Determined22/zh-NER-TF#97]
Traceback (most recent call last):
  File "main.py", line 121, in <module>
    PER, LOC, ORG = get_entity(tag, demo_sent)
  File "/data/user/fengchangmin/zh-NER-TF/utils.py", line 15, in get_entity
    PER = get_PER_entity(tag_seq, char_seq)
  File "/data/user/fengchangmin/zh-NER-TF/utils.py", line 33, in get_PER_entity
    per += char
UnboundLocalError: local variable 'per' referenced before assignment

**Comment by ctgu-huamei** [comment]
我也出现了这个问题，请问楼主解决了吗

**Comment by luoluraro** [comment]
在utils.py 里每个get_per/loc/org 的for循环里加入一个global声明 global per这样变全局变量

**Comment by ctgu-huamei** [comment]
> 在utils.py 里每个get_per/loc/org 的for循环里加入一个global声明 global per这样变全局变量

你好，我在我的代码按照你所说的更改了，但是在demo调用的时候，它并没有给出任何预测，请问你具体是怎么实现的？

**Comment by ctgu-huamei** [comment]
> 在utils.py 里每个get_per/loc/org 的for循环里加入一个global声明 global per这样变全局变量
> 
> 你好，我在我的代码按照你所说的更改了，但是在demo调用的时候，它并没有给出任何预测，请问你具体是怎么实现的？
> 
> 你好 请问你这个问题解决了么

不好意思，现在才看到。之前调试是有成功，但是在新增过多get_per的是想要抓取位置信息，最后代码出现维度错误，不过我换了一份开源代码[https://github.com/zjy-ucas/ChineseNER](url)，这份开源代码无须自写代码打印预测实体，唯一的缺点是如果不做更改只能预测数据是BIOES的数据格式（可能是我自己没读太懂，因为我看见作者是有给出BIOES和BIO的格式转换，但是在预测的时候，作者的确只写了BIOES格式的打印，在result_to_json函数），训练两种格式都可以。 可以自己手动修改utils.py 里面的result_to_json 函数，达到打印BIO格式的预测实体目的。最后请问你在中文命名实体方面有什么内容可以分享的呢？

**Comment by Niuht** [comment]
> 
> 
> > 在utils.py 里每个get_per/loc/org 的for循环里加入一个global声明 global per这样变全局变量
> > 你好，我在我的代码按照你所说的更改了，但是在demo调用的时候，它并没有给出任何预测，请问你具体是怎么实现的？
> > 你好 请问你这个问题解决了么
> 
> 不好意思，现在才看到。之前调试是有成功，但是在新增过多get_per的是想要抓取位置信息，最后代码出现维度错误，不过我换了一份开源代码[https://github.com/zjy-ucas/ChineseNER](url)，这份开源代码无须自写代码打印预测实体，唯一的缺点是如果不做更改只能预测数据是BIOES的数据格式（可能是我自己没读太懂，因为我看见作者是有给出BIOES和BIO的格式转换，但是在预测的时候，作者的确只写了BIOES格式的打印，在result_to_json函数），训练两种格式都可以。 可以自己手动修改utils.py 里面的result_to_json 函数，达到打印BIO格式的预测实体目的。最后请问你在中文命名实体方面有什么内容可以分享的呢？

感谢回复，后来发现我的这个问题是因为标注的格式没有统一，已经解决了。
